# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
workspace 'TechnicalTest.xcworkspace'
use_frameworks!
inhibit_all_warnings!

def di
  pod "Resolver"
end

def network
  pod 'Alamofire'
end

def allPods
  network
  di
end

target 'TechnicalTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  allPods
  target 'TechnicalTestTests' do
    inherit! :search_paths
    allPods
  end
  
  target 'TechnicalTestUITests' do
    # Pods for testing
  end
  
end


target 'TechnicalTestCore' do
  inherit! :search_paths
  project '/Users/leonardborrego/Documents/TechnicalTest/TechnicalTestCore/TechnicalTestCore.xcodeproj'
  allPods
  
  target 'TechnicalTestCoreTests' do
    inherit! :search_paths
    allPods #needed again for this target
  end
  
end

target 'TechnicalTestData' do
  inherit! :search_paths
  project '/Users/leonardborrego/Documents/TechnicalTest/TechnicalTestData/TechnicalTestData.xcodeproj'
  allPods
  
  target 'TechnicalTestDataTests' do
    inherit! :search_paths
    allPods #needed again for this target
  end
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # some older pods don't support some architectures, anything over iOS 11 resolves that
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['CLANG_ENABLE_CODE_COVERAGE'] = 'NO'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
    if ['PactConsumerSwift', 'Embassy'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end
  end
end
